# Generated by Django 3.0 on 2020-06-16 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelAnimal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('animal_label', models.IntegerField(default='')),
                ('animal_name', models.CharField(default='', max_length=50)),
                ('animal_title', models.CharField(default='', max_length=300)),
                ('animal_disc', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='ModelFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='documents/')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
