# Generated by Django 3.2.5 on 2021-12-24 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelanimal',
            name='animal_disc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='modelanimal',
            name='animal_label',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='modelanimal',
            name='animal_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='modelanimal',
            name='animal_title',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='modelfile',
            name='image',
            field=models.ImageField(upload_to='documents/'),
        ),
    ]
